spring:
  datasource:
    url: jdbc:h2:mem:security
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  logging.level:
    org.hibernate.SQL: debug
  h2:
    console:
      path: /h2-console
      enabled: true